### ISSUE TITLE
409 Conflict when creating a directory

### ISSUE THREAD

**Issue by irfanfuard** [perry-mitchell/webdav-client#112]
Any idea why the 409 conflict error occurs when creating a directory? 
'{ Error: Invalid response: 409 Conflict
    at handleResponseCode (C:\Pearson\Projects\CoCo\Branches\cs-memphis-integration\coco-content-service\node_modules\webdav\dist\response.js:7:15)
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 409 }
(node:13648) UnhandledPromiseRejectionWarning: 409
(node:13648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)'

My requirement is to loop a list of directories to be created and in the process create those directories if it's not already created. Any leads as to what could be the issue and what I am doing wrong? Below is my code,

**Comment by perry-mitchell** [comment]
I don’t see any code sorry - did you forget to add it?

**Comment by perry-mitchell** [comment]
I'm not exactly sure on what limitations your server might be putting in place, but you're actually synchronously calling _create_ on all those directories. You probably want something like the following:

```javascript
const selectedMemphisContent = params.selectedMemphisContent;
let work = Promise.resolve();
selectedMemphisContent.forEach(directory => {
  work = work
	.then(() => client.createDirectory(directory))
	.then(() => {
        console.log(`Created: ${directory}`);
    });
});
work.then(() => {
    console.log("Finished.");
});
```

Also, make sure that the directories you're creating are correct. They should be relative to the server root. If you're connecting to a webdav service at `https://test.com/some/dir` then your directories **should not include** `/some/dir`.
