### ISSUE TITLE
Using correct username and password results in 401 Unauthorized

### ISSUE THREAD

**Issue by Freir96** [perry-mitchell/webdav-client#212]
I have a webdav-server set up locally, and I tested it with Windows file explorer, but using the same username and password in the code from example:
`const { createClient } = require('webdav');

async function dav() {
    const client = createClient(
        // '/webdav/',
        'http://localhost:2000',
        {
            username: 'username',
            password: 'password'
        }
    );
    //let res = await client.exists("/")
    //console.log('bip', res);
    // Get directory contents
    const directoryItems = await client.getDirectoryContents('/');
    console.log(directoryItems);
}
try {
    dav()
}
catch (e) {
    console.log('err', e)
}`

it shows 'Error: Request failed with status code 401'

**Comment by perry-mitchell** [comment]
@Freir96 Apologies for not seeing this sooner. Not sure if you're still having this issue or have moved on. Are you sure that the service's root as at `http://localhost:2000`? This is usually a sign that the authentication pattern was rejected.. When specifying in this client, the username and password, by default signifies that the authentication will be [basic](https://en.wikipedia.org/wiki/Basic_access_authentication). It may be that your webdav service doesn't support this form of authentication.

**Comment by Freir96** [comment]
No, I don't have this issue anymore. I have switched to production server, so it could have been some problem with webdav-server.

**Comment by tipleyg** [comment]
I am having this issue, though. I'm running it locally on my machine but not targeting localhost.
![image](https://user-images.githubusercontent.com/44440231/91909048-23d7e600-ec72-11ea-9b20-a6b8046fc105.png)

`const wfs = require("webdav-fs")(
        "https://store-du09xubjip.mybigcommerce.com/dav", {
            "username": "redacted",
            "password": "redacted"
        }
    );

async function writeExport(exportStr) {
    const path = '/content/searchspring/example.json';
    
    try {
        wfs.writeFile(path, exportStr, err => { 
            if (err) throw err;
            output.info("\r\nDone writing"); // Success 
        });
    } catch(e) {
        console.debug(e);
    }
}

!async function main() {
    writeExport('test');
}();`

Here are the error messages:
`
(node:32172) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\adapters\http.js:
237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:32172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 2)
(node:32172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by tipleyg** [comment]
I am getting this error, though. The WebDAV server type is HTTPS/SSL and when I connect to it in CyberDuck, it uses port 443.
![image](https://user-images.githubusercontent.com/44440231/91909588-1f5ffd00-ec73-11ea-9877-95c04ce82225.png)

 I'm running my script on my machine but it is



``
const wfs = require("webdav-fs")(
        "https://store-du09xubjip.mybigcommerce.com/dav", {
            "username": "redacted",
            "password": "redacted"
        }
    );

async function writeExport(exportStr) {
    const path = '/content/searchspring/example.json';
    
    try {
        wfs.writeFile(path, exportStr, err => { 
            if (err) throw err;
            output.info("\r\nDone writing"); // Success 
        });
    } catch(e) {
        console.debug(e);
    }
}

!async function main() {
    writeExport('test');
}
``

Here are the error messages in the terminal:
`
(node:32172) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\IT\Documents\nexus-bigcommerce\node_modules\axios\lib\adapters\http.js:
237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:32172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 2)
(node:32172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.
`
