### ISSUE TITLE
Error loading client 

### ISSUE THREAD

**Issue by andryshok** [perry-mitchell/webdav-client#358]
`const { createClient } = require("webdav");

const client = createClient(
    "url",
    {
        username: "",
        password: "!"
    }
);`

node app.js
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: e:\OpenServer3\domains\test.zz\node_modules\webdav\dist\node\index.js
require() of ES modules is not supported.
require() of e:\OpenServer3\domains\test.zz\node_modules\webdav\dist\node\index.js from e:\OpenServer3\domains\test.zz\app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from e:\OpenServer3\domains\test.zz\node_modules\webdav\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (e:\OpenServer3\domains\test.zz\app.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'

**Comment by perry-mitchell** [comment]
V5 requires ESM to work, which is why you're getting this error. You must either upgrade your project to use ESM or use Webpack or rollup to build it.
